version: '3.8'

services:
  ess-cap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ess-cap
    restart: unless-stopped
    networks:
      nginx-proxy:
        ipv4_address: 172.20.0.17
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://ess.arkana.my
      - VITE_ODOO_URL=https://arkana.co.id
      - VITE_ODOO_DB=odoo16_prod_arkana
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    expose:
      - "80"

networks:
  nginx-proxy:
    external: true 